# 1.全连接层：正向传播，随机初始化w，b

In [44]:
# 全连接层：正向传播
import numpy as np
x = np.arange(1,11,1).reshape(2,5)
print ("上层输出是2个batch，每个batch有5个向量：\n" + str(x))

ww = std * np.random.randn(5,3)
bb = std * np.zeros(3)
print ("\n随机初始化w的参数的shape是：\n" + str(ww.shape))
print ("\n随机初始化w的参数是：\n" + str(ww))
print ("\n随机初始化b的参数的shape是：\n" + str(bb.shape))
print ("\n随机初始化b的参数是：\n" + str(bb))
a = x.dot(ww) + bb
print ("\n全连接之后输出层的shape是：\n" + str(a.shape))
print ("\n全连接之后输出是：\n" + str(a))



上层输出是2个batch，每个batch有5个向量：
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

随机初始化w的参数的shape是：
(5, 3)

随机初始化w的参数是：
[[ -2.02246258e-04  -2.86134686e-05   5.67536552e-05]
 [ -2.65147732e-05   3.46693399e-05  -4.84865213e-05]
 [ -8.56741462e-05  -1.36582254e-04  -1.63278178e-04]
 [  7.67300884e-05   4.15051110e-05   3.05435127e-05]
 [  2.03954211e-05   7.60062287e-05  -2.58280679e-04]]

随机初始化b的参数的shape是：
(3,)

随机初始化b的参数是：
[ 0.  0.  0.]

全连接之后输出层的shape是：
(2, 3)

全连接之后输出是：
[[-0.0001034   0.00017703 -0.00169928]
 [-0.00118995  0.00011195 -0.00361302]]


# 2.全连接，反向传播

In [62]:
# 1.对上一层的输出（即当前层的输入）求导
loss = np.arange(0,1.2,0.2).reshape(2,3)
print ("假设下层传过来的loss是：\n" + str(loss))
residual_x = loss.dot(ww.T)
print ("\n1.对上层的输出求导值的shape：\n" + str(residual_x.shape))
print ("\n对上层的输出求导：\n" + str(residual_x))



# 2.对权重系数W求导
lr = 0.01
reg = 0.75
prev_grad_w = np.zeros_like(ww)
ww -=  lr * (x.T.dot(loss) + prev_grad_w * reg)
prev_grad_w = ww

print ("\n2.对权重系数W求导之后更新的W值的shape：\n" + str(prev_grad_w.shape))
print ("\n对权重系数W求导之后更新的W：\n" + str(prev_grad_w))

# 3.对偏置系数b求导
prev_grad_b = np.zeros_like(bb)
bb -= lr * (np.sum(loss, axis=0))
prev_grad_b = bb

print ("\n3.对偏置系数b求导之后更新的b值的shape：\n" + str(prev_grad_b.shape))
print ("\n对偏置系数b求导之后更新的b：\n" + str(prev_grad_b))

假设下层传过来的loss是：
[[ 0.   0.2  0.4]
 [ 0.6  0.8  1. ]]

1.对上层的输出求导值的shape：
(2, 5)

对上层的输出求导：
[[-0.17798302 -0.21601246 -0.25409263 -0.29197948 -0.33008811]
 [-0.62808748 -0.75603666 -0.88432395 -1.01189021 -1.14018524]]

2.对权重系数W求导之后更新的W值的shape：
(5, 3)

对权重系数W求导之后更新的W：
[[-0.21620225 -0.30002861 -0.38394325]
 [-0.25202651 -0.35996533 -0.46804849]
 [-0.28808567 -0.42013658 -0.55216328]
 [-0.32392327 -0.47995849 -0.63596946]
 [-0.3599796  -0.53992399 -0.72025828]]

3.对偏置系数b求导之后更新的b值的shape：
(3,)

对偏置系数b求导之后更新的b：
[-0.036 -0.06  -0.084]


# 3.numpy 的flatten层：将每个batch里的每个channel安顺序按行展开

In [63]:
# numpy 的flatten层：将每个batch里的每个channel安顺序按行展开
import numpy as np
q = np.arange(1,25,1).reshape(2,3,2,2)
print (q)
print (q.reshape(2,3*2*2))

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]

  [[ 9 10]
   [11 12]]]


 [[[13 14]
   [15 16]]

  [[17 18]
   [19 20]]

  [[21 22]
   [23 24]]]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
