# 1.softmax

In [64]:
# import numpy as np
a = np.array([[-0.69314718 ,-1.60943791, -1.2039728],[-0.22314355, -2.30258509, -2.30258509]])
print ("数组a的值为：\n" + str(a))
print ("找出a中每行最大值：")
print (np.max(a, axis=1).reshape(-1,1))
b = a - np.max(a, axis=1).reshape(-1, 1)
print ("a中每行均减去本行最大值后的数组b：")
print (b)
a_softmax = np.exp(a) / np.sum(np.exp(a), axis=1).reshape(-1, 1)
print ("对数组a进行softmax：")
print (a_softmax)
b_softmax = np.exp(b) / np.sum(np.exp(b), axis=1).reshape(-1, 1)
print ("对去掉最大值的进行softmax：")
print (b_softmax)


数组a的值为：
[[-0.69314718 -1.60943791 -1.2039728 ]
 [-0.22314355 -2.30258509 -2.30258509]]
找出a中每行最大值：
[[-0.69314718]
 [-0.22314355]]
a中每行均减去本行最大值后的数组b：
[[ 0.         -0.91629073 -0.51082562]
 [ 0.         -2.07944154 -2.07944154]]
对数组a进行softmax：
[[ 0.5  0.2  0.3]
 [ 0.8  0.1  0.1]]
对去掉最大值的进行softmax：
[[ 0.5  0.2  0.3]
 [ 0.8  0.1  0.1]]


可以看到减不减去每行的最大值对softmax结果都没有影响，但是这里softmax之前还是要加这一步骤，为了去除数据里的噪声。

# 2.Cross Entropy

In [68]:
print ("我们上次得到的softmax为：")
print (b_softmax)
d = np.log10(b_softmax)                         # log下什么都不写默认是自然对数e为底 ，np.log10()是以10为底
print ("对softmax取ln：")
print (d)
print ("找出softmax中每行我们标签概率最大的两个数，也就是第一行的第0个，第二行的第0个：")
print (b_softmax[range(2), list([0,0])])
c = np.log10(b_softmax[range(2), list([0,0])])
print ("分别对这两个数进行ln：")
print (c)
print ("最后，因为这两行是一个batch的两个，所以，加和去平均，得到的就是Loss：")
print (-np.sum(np.log10(b_softmax[range(2), list([0,0])]))*(1/2))

我们上次得到的softmax为：
[[ 0.5  0.2  0.3]
 [ 0.8  0.1  0.1]]
对softmax取ln：
[[-0.30103    -0.69897    -0.52287874]
 [-0.09691001 -1.         -1.        ]]
找出softmax中每行我们标签概率最大的两个数，也就是第一行的第0个，第二行的第0个：
[ 0.5  0.8]
分别对这两个数进行ln：
[-0.30103    -0.09691001]
最后，因为这两行是一个batch的两个，所以，加和去平均，得到的就是Loss：
0.198970004736
